name: arashi-co # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Arashi
summary: Chronicles of the Stormbringer - Unleash the Power Within # 79 char long summary
description: |
   Chronicles of the Stormbringer invites you to wield elemental powers in a journey through a world torn by cataclysmic forces. 
   Master the elements, unravel the mysteries of the storm, and forge your legend amidst the chaos.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  arashi-co:
    command: bin/arashi-co-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  arashi-co:
    plugin: dump
    source: .
    organize:
      arashi-co-bin: bin/
